### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by Donokami** [deepinstruction/deepnude_official#10]
When I try to `python3 main.py`, I've got this error, even with the default `input.png`
```
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Executing phase: mask_to_maskref
Executing phase: maskref_to_maskdet
Executing phase: maskdet_to_maskfin
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 21, in main
    watermark = process(dress)
  File "/content/deepnude_official/run.py", line 144, in process
    maskfin = create_maskfin(maskref, maskdet)
  File "/content/deepnude_official/opencv_transform/maskdet_to_maskfin.py", line 34, in create_maskfin
    bodypart_list = extractAnnotations(maskdet);
  File "/content/deepnude_official/opencv_transform/maskdet_to_maskfin.py", line 101, in extractAnnotations
    tits_list = findBodyPart(maskdet, "tit")
  File "/content/deepnude_official/opencv_transform/maskdet_to_maskfin.py", line 168, in findBodyPart
    contours, hierarchy = cv2.findContours(color_mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)
```

**Comment by Marineeee** [comment]
I've got the same error, i'm looking for what is wrong with the code

**Comment by SunnerLi** [comment]
Hi @Donokami @Marineeee ,
I didn't run the DeepNude code actually.
According to official OpenCV [document](https://docs.opencv.org/3.1.0/d3/dc0/group__imgproc__shape.html#ga17ed9f5d79ae97bd4c7cf18403e1689a),
The cv2.findContours will return three objects.
Maybe we can revise the `opencv_transform/maskdet_to_maskfin.py` line 168 as following:
```
dummy_img, contours, hierarchy = cv2.findContours(color_mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
```

**Comment by Marineeee** [comment]
The picture need to be 512x512, if it's higher there will be this error ( i didn't try behind 512 )

**Comment by Donokami** [comment]
@SunnerLi Your solution worked. Maybe a Pull request to fix this issue?

**Comment by rom1504** [comment]
you need opencv 4

**Comment by niko247** [comment]
yeah, on opencv4 it returns 2 values so your pull request is not needed. Use: pip install opencv-python

**Comment by rayryeng** [comment]
You can just do `contours, hierarchy = cv2.findContours(color_mask,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)[-2:]`.  This will work regardless of the version (3 or 4) and will always grab the last two outputs so no dummy variable for the first element of the tuple if you're using v3 is required.
