### ISSUE TITLE
error loading DLL ?

### ISSUE THREAD

**Issue by biaggio12** [deepinstruction/deepnude_official#18]
I have this problem, can't get it to work. Any ideas ?
`Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from run import process
  File "C:\Users\Blazej\Documents\deep\deepnude_official\run.py", line 4, in <module>
    from gan import DataLoader, DeepModel, tensor2im
  File "C:\Users\Blazej\Documents\deep\deepnude_official\gan.py", line 4, in <module>
    import torchvision.transforms as transforms
  File "C:\Users\Blazej\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\__init__.py", line 1, in <module>
    from torchvision import models
  File "C:\Users\Blazej\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\models\__init__.py", line 1, in <module>
    from .alexnet import *
  File "C:\Users\Blazej\AppData\Local\Programs\Python\Python36\lib\site-packages\torchvision\models\alexnet.py", line 1, in <module>
    import torch.nn as nn
  File "C:\Users\Blazej\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\__init__.py", line 79, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified procedure could not be found.`

**Comment by marshin77** [comment]
same problem will let you know if i find a fix

**Comment by marshin77** [comment]
fixed!
pip3 uninstall torch

pip3  uninstall torchvision

pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-win_amd64.whl

pip3 install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp37-cp37m-win_amd64.whl

**Comment by biaggio12** [comment]
unfortunately 
`ERROR: torchvision-0.3.0-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform.`

**Comment by AlexHaber** [comment]
Try this

pip3 install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-win_amd64.whl
pip3 install https://download.pytorch.org/whl/cpu/torchvision-0.3.0-cp36-cp36m-win_amd64.whl
