### ISSUE TITLE
Getting error mask to maskref : (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'cv::binary_op'

### ISSUE THREAD

**Issue by ebenezergraymes** [deepinstruction/deepnude_official#24]
Hello ! I got sometimes this error I'm not sure why ? I tried so resize the input to got a 512*512 and it seemed to work for some pictures but not for all. That's weird.
Any ideas ?

Traceback (most recent call last):
  File "D:\Users\____\Documents\GitHub\deepnude_official\main.py", line 30, in <module>
    main()
  File "D:\Users\_____\Documents\GitHub\deepnude_official\main.py", line 21, in main
    watermark = process(dress)
  File "D:\Users\_____\Documents\GitHub\deepnude_official\run.py", line 140, in process
    maskref = create_maskref(mask, correct)
  File "D:\Users\_____\Documents\GitHub\deepnude_official\opencv_transform\mask_to_maskref.py", line 38, in create_maskref
    res2 = cv2.bitwise_and(green, green, mask = green_mask)
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\core\src\arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'cv::binary_op'

**Comment by alextooter** [comment]
it limits to 512x512 because the last step add watermark to nude image,the watermark image it self is 512x512 size.

So you can remove the last step,and search 512 in the .py,change it to input.png's x and y. This change make it can accept all image no matter what size is.

**Comment by MartinMa94** [comment]
> it limits to 512x512 because the last step add watermark to reslut image,the watermark image it self is 512x512 size.
> 
> So you can search 512 in the .py,change it to input.png's x and y. This change make it can accept all image no matter what size is.

I tried to change 512px to dynamic x and y of png, but it still has something wrong the size of mask. It seems that the mask's x and y is 512px in hardcode, but I just found three places for "512" str in the project. I wonder how do you make it be dynamic?

**Comment by free9003724** [comment]
I also want to ask the same question: Now I will reduce the size of input.png by half, which is 256X256. Running main.py will also prompt this same error.

**Comment by MartinMa94** [comment]
> I also want to ask the same question: Now I will reduce the size of input.png by half, which is 256X256. Running main.py will also prompt this same error.

The size of 'mask' maybe hardcoding to 512px, I guess.

**Comment by alextooter** [comment]
> > it limits to 512x512 because the last step add watermark to reslut image,the watermark image it self is 512x512 size.
> > So you can search 512 in the .py,change it to input.png's x and y. This change make it can accept all image no matter what size is.
> 
> I tried to change 512px to dynamic x and y of png, but it still has something wrong the size of mask. It seems that the mask's x and y is 512px in hardcode, but I just found three places for "512" str in the project. I wonder how do you make it be dynamic?

def getxy():

    img = cv2.imread("input.jpg")
    return img.shape[0],img.shape[1]

opencv_transform/mask_to_maskref.py:19:	
x,y = getxy() 
green = np.zeros((x,y,3), np.uint8)

opencv_transform/maskdet_to_maskfin.py:31:	
x,y = getxy()
details = np.zeros((x,y,3), np.uint8)

comment those three line in run.py:146
		#nude_to_watermark phase (opencv)
		#elif (phase == "nude_to_watermark"):
			#watermark = create_watermark(nude)


plus, you can modify main.py to accept jpg since most images are jpeg file.
dress	=	cv2.imread("input.jpg")

**Comment by Freedzy** [comment]
See #30 pull request - I removed the limitation
