### ISSUE TITLE
it worked with input.png from the repo, but not with random picture

### ISSUE THREAD

**Issue by Dysar** [deepinstruction/deepnude_official#9]
Any OpenCV experts to solve this?

```
$ python3 main.py
Executing phase: dress_to_correct
Executing phase: correct_to_mask
Executing phase: mask_to_maskref
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    main()
  File "main.py", line 21, in main
    watermark = process(dress)
  File "/home/d/deepnude_official/run.py", line 140, in process
    maskref = create_maskref(mask, correct)
  File "/home/d/deepnude_official/opencv_transform/mask_to_maskref.py", line 37, in create_maskref
    res1 = cv2.bitwise_and(cv_correct, cv_correct, mask = green_mask_inv)
cv2.error: OpenCV(4.1.0) /io/opencv/modules/core/src/arithm.cpp:245: error: (-215:Assertion failed) (mtype == CV_8U || mtype == CV_8S) && _mask.sameSize(*psrc1) in function 'binary_op'
```

**Comment by huguesdevimeux** [comment]
The picture must be in 512x512 format
